"""oya ghen ghen

Revision ID: 5ed9aad7365d
Revises: c21efc362874
Create Date: 2025-10-19 23:35:58.428450

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ed9aad7365d'
down_revision = 'c21efc362874'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('unit', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hou_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['hou_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('unit', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('hou_id')

    # ### end Alembic commands ###
